#! /bin/sh
sxhkd &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

##### BSPC ###
##INTERNAL_MONITOR="eDP1"
##EXTERNAL_MONITOR="HDMI-1"
##
##monitor_add() {
##  # Move first 5 desktops to external monitor
##  for desktop in $(bspc query -D --names -m "$INTERNAL_MONITOR" | sed 5q); do
##    bspc desktop "$desktop" --to-monitor "$EXTERNAL_MONITOR"
##  done
##  # Remove default desktop created by bspwm
##  bspc desktop Desktop --remove
##  # reorder monitors
##  bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
##}
##
##monitor_remove() {
##  # Add default temp desktop because a minimum of one desktop is required per monitor
##  bspc monitor "$EXTERNAL_MONITOR" -a Desktop
##
##  # Move all desktops except the last default desktop to internal monitor
##  for desktop in $(bspc query -D -m "$EXTERNAL_MONITOR");	do
##		bspc desktop "$desktop" --to-monitor "$INTERNAL_MONITOR"
##	done
##
##  # delete default desktops
##  bspc desktop Desktop --remove
##  # reorder desktops
##  bspc monitor "$INTERNAL_MONITOR" -d I II III IV V VI VII VIII IX X
##}
##
##if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
##  # set xrandr rules for docked setup
##  xrandr --output "$INTERNAL_MONITOR" --mode 1366x768 --pos 0x0 --rotate normal --output "$EXTERNAL_MONITOR" --primary --mode 1280x800 --rotate normal
##  if [[ $(bspc query -D -m "${EXTERNAL_MONITOR}" | wc -l) -ne 5 ]]; then
##    monitor_add
##  fi
##  bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
##else
##  # set xrandr rules for mobile setup
##  xrandr --output "$INTERNAL_MONITOR" --primary --mode 1366x768 --pos 0x0 --rotate normal --output "$EXTERNAL_MONITOR" --off
##  if [[ $(bspc query -D -m "${INTERNAL_MONITOR}" | wc -l) -ne 10 ]]; then
##    monitor_remove
##  fi
##fi
##
### Kill and relaunch polybar
##killall -q polybar
##while pgrep -u $UID -x polybar > /dev/null; do sleep 2; done
##if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
##  polybar --reload primary -c ~/.config/polybar/config.ini </dev/null >/var/tmp/polybar-primary.log 2>&1 200>&- &
##  polybar --reload secondary -c ~/.config/polybar/config.ini </dev/null >/var/tmp/polybar-secondary.log 2>&1 200>&- &
##else
##  polybar --reload primary -c ~/.config/polybar/config.ini </dev/null >/var/tmp/polybar-primary.log 2>&1 200>&- &
##fi
##
bspc config border_width        2.5
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

##Color settings
bspc config focused_border_color "#74342B"

##Rules
bspc rule -a Blueman-manager state=floating rectangle=620x336+375+240
bspc rule -a Pavucontrol state=floating rectangle=620x336+375+240

bspc config focus_follows_pointer true 

startx
polybar --reload &
nitrogen --restore
picom
